name: Build images

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt install parted wget dosfstools zip

      # Build Images
      # Note: Uploading zip file artifact will be double zip. Do not delete .img file
      # See https://github.com/actions/upload-artifact#zipped-artifact-downloads
      - name: Build Raspberry Pi Image
        run: |
          sudo bash create-image rpi
          zip -v rpi-archlinux.img.zip rpi-archlinux.img

      - name: Build Raspberry Pi 2/3 Image
        run: |
          sudo bash create-image rpi-2
          zip -v rpi-2-archlinux.img.zip rpi-2-archlinux.img

      - name: Build Raspberry Pi 4 Image
        run: |
          sudo bash create-image rpi-4
          zip -v rpi-4-archlinux.img.zip rpi-4-archlinux.img

      # Note: This won't work on RPi4 as it need to modify /etc/fstab.
      - name: Build Raspberry Pi 3 AArch64 Image
        run: |
          sudo bash create-image rpi-aarch64
          sudo mv rpi-aarch64-archlinux.img rpi-3-aarch64-archlinux.img
          zip -v rpi-3-aarch64-archlinux.img.zip rpi-3-aarch64-archlinux.img

      # Hacky way to patch fstab for rpi4. as RPi3 has different SD block device compared to RPi3
      # As previous step wasn't unmount volume after build. Patch directly and build image.
      - name: Build Raspberry Pi 4 AArch64 Image
        run: |
          sed -i 's/mmcblk0/mmcblk1/g' mnt/etc/fstab
          tar -xpf "rpi-4-aarch64-archlinux.img" -C mnt 2> >(grep -v "Ignoring unknown extended header keyword")
          zip -v rpi-4-aarch64-archlinux.img.zip rpi-4-aarch64-archlinux.img


      # Upload artifacts
      - name: Upload Raspberry Pi Image artifact
        uses: actions/upload-artifact@v2
        with:
          name: rpi-archlinux.img
          path: rpi-archlinux.img
      
      - name: Upload Raspberry Pi 2/3 Image artifact
        uses: actions/upload-artifact@v2
        with:
          name: rpi-2-archlinux.img
          path: rpi-2-archlinux.img

      - name: Upload Raspberry Pi 4 Image artifact
        uses: actions/upload-artifact@v2
        with:
          name: rpi-4-archlinux.img
          path: rpi-4-archlinux.img

      - name: Upload Raspberry Pi 3 AArch64 Image artifact
        uses: actions/upload-artifact@v2
        with:
          name: rpi-3-aarch64-archlinux.img
          path: rpi-3-aarch64-archlinux.img

      - name: Upload Raspberry Pi 4 AArch64 Image artifact
        uses: actions/upload-artifact@v2
        with:
          name: rpi-4-aarch64-archlinux.img
          path: rpi-4-aarch64-archlinux.img


      # Upload to release
      - name: Upload images to release
        uses: softprops/action-gh-release@v0.1.6
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            rpi-archlinux.img.zip
            rpi-2-archlinux.img.zip
            rpi-4-archlinux.img.zip
            rpi-3-aarch64-archlinux.img.zip
            rpi-4-aarch64-archlinux.img.zip
        env:
          GITHUB_TOKEN: ${{ github.token }}
