name: Build images

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt install parted wget dosfstools zip

      # Build Images
      # Note: Uploading zip file artifact will be double zip. Do not delete .img file
      # See https://github.com/actions/upload-artifact#zipped-artifact-downloads
      - name: Build Raspberry Pi Image
        run: |
          sudo bash create-image rpi
          zip -v rpi-archlinux.img.zip rpi-archlinux.img

      - name: Build Raspberry Pi 2/3 Image
        run: |
          sudo bash create-image rpi-2
          zip -v rpi-2-archlinux.img.zip rpi-2-archlinux.img

      - name: Build Raspberry Pi 4 Image
        run: |
          sudo bash create-image rpi-4
          zip -v rpi-4-archlinux.img.zip rpi-4-archlinux.img

      # Note: This won't work on RPi4 as it need to modify /etc/fstab.
      - name: Build Raspberry Pi AArch64 Image
        run: |
          sudo bash create-image rpi-aarch64
          zip -v rpi-aarch64-archlinux.img.zip rpi-aarch64-archlinux.img


      # Upload artifacts
      - name: Upload Raspberry Pi Image artifact
        uses: actions/upload-artifact@v2
        with:
          name: rpi-archlinux.img
          path: rpi-archlinux.img
      
      - name: Upload Raspberry Pi 2/3 Image artifact
        uses: actions/upload-artifact@v2
        with:
          name: rpi-2-archlinux.img
          path: rpi-2-archlinux.img

      - name: Upload Raspberry Pi 4 Image artifact
        uses: actions/upload-artifact@v2
        with:
          name: rpi-4-archlinux.img
          path: rpi-4-archlinux.img

      - name: Upload Raspberry Pi AArch64 Image artifact
        uses: actions/upload-artifact@v2
        with:
          name: rpi-aarch64-archlinux.img
          path: rpi-aarch64-archlinux.img


      # Upload to release
      - name: Upload images to release
        uses: softprops/action-gh-release@v0.1.6
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            rpi-archlinux.img.zip
            rpi-2-archlinux.img.zip
            rpi-4-archlinux.img.zip
            rpi-aarch64-archlinux.img.zip
